# Generated by Django 5.1.6 on 2025-03-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaFormativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('saidas_profissionais', models.TextField()),
                ('carga_horaria', models.IntegerField()),
                ('disciplinas', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='ofertas/')),
            ],
        ),
    ]
